project:
  type: book

book:
  title: "STAT303-1"
  author: "Arvind Krishna and Arend Kuyper"
  date: "9/20/2022"
  chapters:
    - index.qmd
    - Introduction to Python and Jupyter Notebooks.ipynb
    - data_structures.ipynb
    - Chap 2 Reading data.ipynb
    - NumPy.ipynb
    - Pandas.ipynb
    - Data visualization.ipynb
    - Data cleaning and preparation.ipynb
    - Data wrangling.ipynb
    - Data aggregation.ipynb
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



