project:
  type: book

book:
  title: "stats"
  author: "Jane Doe"
  date: "7/27/2022"
  chapters:
    - index.qmd
    - data_structures.ipynb
    - Chap 2 Reading data.ipynb
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



