project:
  type: book

book:  
  title: "Introduction to Data Science with Python"
  logo: 'NU_Stat_logo.png'
  author: "Arvind Krishna, and Arend Kuyper"
  date: "9/20/2022"
  chapters:
    - index.qmd
    - part: 'Quick overview: Python programming'
      chapters:
        - Introduction to Python and Jupyter Notebooks.ipynb
        - data_structures.ipynb
    - part: 'Exploratory data analysis'
      chapters:
        - Reading data.ipynb
        - NumPy.ipynb
        - Pandas.ipynb
        - Data visualization.ipynb
        - Data cleaning and preparation.ipynb
        - Data wrangling.ipynb
        - Data aggregation.ipynb
        - Datasets.ipynb
    - part: 'Assignments' 
      chapters:
        - Assignment 4 (Data Visualization).ipynb
  appendices:
    - student_solutions.ipynb
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



